# Generated by Django 5.0.7 on 2024-08-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
